### ISSUE TITLE
執行一陣子會關閉!?

### ISSUE THREAD

**Issue by wastacat** [nicewsyly/ECO#11]
請問這樣的狀況是!?

![image](https://user-images.githubusercontent.com/33395974/40884011-0153953c-673d-11e8-9621-f09ef63981e1.png)

**Comment by nicewsyly** [comment]
和ipp有关,你检查一下是不是库不对了，定位一下ECO程序里边哪边代码crash了，看一下调用堆栈确定一下吧

在 2018-06-03 14:52:16，"wastacat" <notifications@github.com> 写道：


請問這樣的狀況是!?

**Comment by wastacat** [comment]
感謝你  我都已經解決了 ~
若我想提高速度是要修改共軛梯度反覆運算次數?
還是有其他參數也需要修改呢!?
