### ISSUE TITLE
既然已经用了caffe_cpu版本，为什么不用caffe_gpu版本？

### ISSUE THREAD

**Issue by hset911** [nicewsyly/ECO#2]
或者说是否我自己比较容易实现替换成gpu版本的caffe？

**Comment by nicewsyly** [comment]
在安装好gpu caffe后，设置一下Caffe::set_mode(Caffe::GPU);Caffe::SetDevice(0);就可以使用gpu了

**Comment by hset911** [comment]
@nicewsyly 谢谢，按照你说的成功跑起来了，只不过你们用GPU的宏去控制是否用GPU，会和caffe命名空间的GPU冲突报错，建议修改一下。在我的机器上主要的耗时还是在eco_trainer.train_filter()用牛顿法求解的函数上，平均超过300多ms，能顺便问一下在你们readme中所提到的GPU版本是否考虑用cuda编程优化这块的时间？或者说后面的版本可能会优化哪些部分

**Comment by nicewsyly** [comment]
嗯嗯，我们会尽快修改GPU宏这个问题，另外我们下一步的优化也会重点考虑eco_trainer.train_filter()这一部分
