### ISSUE TITLE
time efficiency?

### ISSUE THREAD

**Issue by minacreft** [nicewsyly/ECO#3]
Thanks for sharing your work~
It seems not as fast as the Matlab version ? ( ~ 6 fps vs. 30 fps  on my PC )
I complied CPU version and turn useDeepFeature=false, imshow is also turned off.
Is there something I missed? Thanks~

**Comment by flyingTan** [comment]
Time-consuming part is training every 5 frames. More specifically, matrix operations of Gaussian conjugate and Newton gradienet iteration are implemented by ourselves. On the contrary, matlab fast matrix  operation by sacrifice certrain accuracy  is faster than ours. So, our training part is much slower than Matlab version.

**Comment by minacreft** [comment]
thanks~
